import 'package:floww/core/achievements/models/achievement.dart';
import 'package:floww/core/achievements/models/achievement_category.dart';
import 'package:floww/core/achievements/models/streak_milestone.dart';

class AchievementsData {
  AchievementsData._();

  static const List<Achievement> achievements = [
    Achievement(
      id: 'first_flame',
      emoji: '🔥',
      title: 'First Flame',
      description: 'Complete a 3-day streak',
      xp: 50,
      category: AchievementCategory.streaks,
      isUnlocked: false,
    ),
    Achievement(
      id: 'week_warrior',
      emoji: '⚡',
      title: 'Week Warrior',
      description: '7-day streak',
      xp: 150,
      category: AchievementCategory.streaks,
      isUnlocked: false,
    ),
    Achievement(
      id: 'fortnight_force',
      emoji: '🏆',
      title: 'Fortnight Force',
      description: '14-day streak',
      xp: 350,
      category: AchievementCategory.streaks,
      isUnlocked: false,
    ),
    Achievement(
      id: 'monthly_master',
      emoji: '🌟',
      title: 'Monthly Master',
      description: '30-day streak',
      xp: 1000,
      category: AchievementCategory.streaks,
      isUnlocked: false,
    ),
    Achievement(
      id: 'first_sweat',
      emoji: '💪',
      title: 'First Sweat',
      description: 'Complete your first workout',
      xp: 25,
      category: AchievementCategory.fitness,
      isUnlocked: false,
    ),
    Achievement(
      id: 'consistent',
      emoji: '🎯',
      title: 'Consistent',
      description: 'Complete 10 workouts',
      xp: 200,
      category: AchievementCategory.fitness,
      isUnlocked: false,
    ),
    Achievement(
      id: 'iron_will',
      emoji: '🏋️',
      title: 'Iron Will',
      description: 'Complete 50 workouts',
      xp: 500,
      category: AchievementCategory.fitness,
      isUnlocked: false,
    ),
    Achievement(
      id: 'century_lifter',
      emoji: '🥇',
      title: 'Century Lifter',
      description: 'Complete 100 workouts',
      xp: 1200,
      category: AchievementCategory.fitness,
      isUnlocked: false,
    ),
    Achievement(
      id: 'habit_starter',
      emoji: '🌱',
      title: 'Habit Starter',
      description: 'Create your first habit',
      xp: 50,
      category: AchievementCategory.habits,
      isUnlocked: false,
    ),
    Achievement(
      id: 'daily_driver',
      emoji: '📅',
      title: 'Daily Driver',
      description: 'Log habits 7 days in a row',
      xp: 100,
      category: AchievementCategory.habits,
      isUnlocked: false,
    ),
    Achievement(
      id: 'habit_stack',
      emoji: '🧱',
      title: 'Habit Stack',
      description: 'Track 5 habits in one day',
      xp: 150,
      category: AchievementCategory.habits,
      isUnlocked: false,
    ),
    Achievement(
      id: 'routine_master',
      emoji: '⚙️',
      title: 'Routine Master',
      description: 'Complete 100 habit logs',
      xp: 600,
      category: AchievementCategory.habits,
      isUnlocked: false,
    ),
    Achievement(
      id: 'personal_best',
      emoji: '📈',
      title: 'Personal Best',
      description: 'Set your first personal record',
      xp: 150,
      category: AchievementCategory.performance,
      isUnlocked: false,
    ),
    Achievement(
      id: 'volume_up',
      emoji: '🛞',
      title: 'Volume Up',
      description: 'Lift 10,000 kg in a week',
      xp: 250,
      category: AchievementCategory.performance,
      isUnlocked: false,
    ),
    Achievement(
      id: 'peak_flow',
      emoji: '🌊',
      title: 'Peak Flow',
      description: 'Reach a 100 Flow Score',
      xp: 300,
      category: AchievementCategory.performance,
      isUnlocked: false,
    ),
    Achievement(
      id: 'recovery_pro',
      emoji: '🧘',
      title: 'Recovery Pro',
      description: 'Reach full recovery on every muscle',
      xp: 200,
      category: AchievementCategory.performance,
      isUnlocked: false,
    ),
    Achievement(
      id: 'clean_plate',
      emoji: '🥗',
      title: 'Clean Plate',
      description: 'Log your first meal',
      xp: 50,
      category: AchievementCategory.nutrition,
      isUnlocked: false,
    ),
    Achievement(
      id: 'hydrated',
      emoji: '💧',
      title: 'Hydrated',
      description: 'Hit your water goal 7 days',
      xp: 125,
      category: AchievementCategory.nutrition,
      isUnlocked: false,
    ),
  ];

  static const List<StreakMilestone> milestones = [
    StreakMilestone(
      emoji: '⚡',
      title: '1 Week Warrior',
      description: '7-day streak',
    ),
    StreakMilestone(
      emoji: '🏆',
      title: '2 Week Champion',
      description: '14-day streak',
    ),
    StreakMilestone(
      emoji: '🔥',
      title: '30-Day Legend',
      description: '30-day streak',
    ),
    StreakMilestone(
      emoji: '🌟',
      title: 'Century Club',
      description: '100-day streak',
    ),
  ];
}
