import 'package:floww/config/constants/app_images.dart';
import 'package:floww/config/entities/workout_exercise_entity.dart';
import 'package:floww/config/entities/workout_program_entity.dart';
import 'package:floww/core/workout/models/exercise.dart';
import 'package:floww/core/workout/models/workout_section_kind.dart';

class WorkoutCatalogData {
  WorkoutCatalogData._();

  static const int version = 1;

  static const List<ExerciseCatalogEntry> exercises = [
    ExerciseCatalogEntry(
      id: 'barbell-back-squat',
      name: 'Barbell Back Squat',
      group: MuscleGroup.legs,
      equipment: Equipment.barbell,
      met: 6,
      muscleShares: {'Quadriceps': 1, 'Glutes': 0.8, 'Hamstrings': 0.5},
      defaultSets: 4,
      defaultReps: 8,
      defaultRestSeconds: 165,
      defaultRepsInReserve: 2,
      defaultWeightKg: 60,
      imageUrl: AppImages.barbellBackSquat,
      mistakes: [
        ExerciseCueEntry(text: 'Heels lifting off ground'),
        ExerciseCueEntry(text: 'Knees caving inward'),
        ExerciseCueEntry(text: 'Not reaching parallel depth'),
        ExerciseCueEntry(text: 'Forward lean of torso'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Feet shoulder-width, toes slightly out'),
        ExerciseCueEntry(text: 'Brace the core before descending'),
        ExerciseCueEntry(text: 'Sit back and down — chest up'),
        ExerciseCueEntry(text: 'Drive through full foot'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Standard or Olympic bar'),
        ExerciseCueEntry(label: 'Weight plates', text: 'Plus collars/clips'),
        ExerciseCueEntry(label: 'Rack', text: 'Squat rack or power rack'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'romanian-deadlift',
      name: 'Romanian Deadlift',
      group: MuscleGroup.legs,
      equipment: Equipment.barbell,
      met: 6,
      muscleShares: {'Hamstrings': 1, 'Glutes': 0.85, 'Back': 0.4},
      defaultSets: 4,
      defaultReps: 12,
      defaultRestSeconds: 120,
      defaultRepsInReserve: 2,
      defaultWeightKg: 50,
      imageUrl: AppImages.romanianDeadlift,
      mistakes: [
        ExerciseCueEntry(text: 'Rounding the lower back'),
        ExerciseCueEntry(text: 'Bending the knees too much'),
        ExerciseCueEntry(text: 'Letting the bar drift forward'),
        ExerciseCueEntry(text: 'Hyperextending at the top'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Hinge from the hips, soft knees'),
        ExerciseCueEntry(text: 'Keep the bar against your legs'),
        ExerciseCueEntry(text: 'Stretch the hamstrings, then drive up'),
        ExerciseCueEntry(text: 'Brace your core throughout'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Standard or Olympic bar'),
        ExerciseCueEntry(label: 'Weight plates', text: 'Plus collars/clips'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'leg-press',
      name: 'Leg Press',
      group: MuscleGroup.legs,
      equipment: Equipment.machine,
      met: 5.5,
      muscleShares: {'Quadriceps': 1, 'Glutes': 0.6, 'Hamstrings': 0.35},
      defaultSets: 4,
      defaultReps: 12,
      defaultRestSeconds: 120,
      defaultRepsInReserve: 2,
      defaultWeightKg: 80,
      imageUrl: AppImages.legPress,
      mistakes: [
        ExerciseCueEntry(text: 'Lifting hips off the seat'),
        ExerciseCueEntry(text: 'Locking out the knees'),
        ExerciseCueEntry(text: 'Partial range of motion'),
        ExerciseCueEntry(text: 'Pushing through the toes'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Feet shoulder-width on the platform'),
        ExerciseCueEntry(text: 'Lower until knees reach 90°'),
        ExerciseCueEntry(text: 'Keep the lower back flat'),
        ExerciseCueEntry(text: 'Drive through mid-foot and heel'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Machine', text: 'Leg press sled'),
        ExerciseCueEntry(label: 'Weight plates', text: 'Loaded per side'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'walking-lunge',
      name: 'Walking Lunges',
      group: MuscleGroup.legs,
      equipment: Equipment.dumbbell,
      met: 5,
      muscleShares: {'Quadriceps': 0.9, 'Glutes': 1, 'Hamstrings': 0.4},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 90,
      defaultRepsInReserve: 3,
      defaultWeightKg: 12,
      imageUrl: AppImages.walkingLunges,
      mistakes: [
        ExerciseCueEntry(text: 'Front knee travelling past the toes'),
        ExerciseCueEntry(text: 'Short, unstable steps'),
        ExerciseCueEntry(text: 'Leaning the torso forward'),
        ExerciseCueEntry(text: 'Rear knee slamming the floor'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Long step, chest tall'),
        ExerciseCueEntry(text: 'Lower until both knees reach 90°'),
        ExerciseCueEntry(text: 'Push through the front heel'),
        ExerciseCueEntry(text: 'Alternate legs each step'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Dumbbells', text: 'One per hand'),
        ExerciseCueEntry(label: 'Space', text: 'Clear walking lane'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'leg-extension',
      name: 'Leg Extension',
      group: MuscleGroup.legs,
      equipment: Equipment.machine,
      met: 4.5,
      muscleShares: {'Quadriceps': 1},
      defaultSets: 3,
      defaultReps: 15,
      defaultRestSeconds: 75,
      defaultRepsInReserve: 2,
      defaultWeightKg: 35,
      imageUrl: AppImages.legExtension,
      mistakes: [
        ExerciseCueEntry(text: 'Swinging the weight up'),
        ExerciseCueEntry(text: 'Pad resting too high on the shin'),
        ExerciseCueEntry(text: 'Dropping the weight on the way down'),
        ExerciseCueEntry(text: 'Lifting the hips off the seat'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Align knees with the machine pivot'),
        ExerciseCueEntry(text: 'Extend fully, pause at the top'),
        ExerciseCueEntry(text: 'Lower under control'),
        ExerciseCueEntry(text: 'Keep the back against the pad'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Machine', text: 'Leg extension machine'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'standing-calf-raise',
      name: 'Standing Calf Raise',
      group: MuscleGroup.legs,
      equipment: Equipment.machine,
      met: 4,
      muscleShares: {'Calves': 1},
      defaultSets: 3,
      defaultReps: 20,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 2,
      defaultWeightKg: 30,
      imageUrl: AppImages.standingCalfRaise,
      mistakes: [
        ExerciseCueEntry(text: 'Bouncing out of the bottom'),
        ExerciseCueEntry(text: 'Bending the knees to cheat'),
        ExerciseCueEntry(text: 'Cutting the range of motion short'),
        ExerciseCueEntry(text: 'Rushing every rep'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Balls of the feet on the platform'),
        ExerciseCueEntry(text: 'Drop the heels for a full stretch'),
        ExerciseCueEntry(text: 'Rise as high as possible, pause'),
        ExerciseCueEntry(text: 'Keep the legs straight'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Machine', text: 'Standing calf raise'),
        ExerciseCueEntry(label: 'Step', text: 'Or raised platform'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'barbell-bench-press',
      name: 'Barbell Bench Press',
      group: MuscleGroup.chest,
      equipment: Equipment.barbell,
      met: 5.5,
      muscleShares: {'Chest': 1, 'Triceps': 0.6, 'Shoulders': 0.5},
      defaultSets: 4,
      defaultReps: 8,
      defaultRestSeconds: 150,
      defaultRepsInReserve: 2,
      defaultWeightKg: 40,
      mistakes: [
        ExerciseCueEntry(text: 'Bouncing the bar off the chest'),
        ExerciseCueEntry(text: 'Flaring the elbows to 90°'),
        ExerciseCueEntry(text: 'Lifting the hips off the bench'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Shoulder blades pinned back and down'),
        ExerciseCueEntry(text: 'Lower to mid-chest under control'),
        ExerciseCueEntry(text: 'Drive the bar back over the shoulders'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Standard or Olympic bar'),
        ExerciseCueEntry(label: 'Bench', text: 'Flat bench with rack'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'incline-db-press',
      name: 'Incline DB Press',
      group: MuscleGroup.chest,
      equipment: Equipment.dumbbell,
      met: 5,
      muscleShares: {'Chest': 1, 'Shoulders': 0.6, 'Triceps': 0.45},
      defaultSets: 3,
      defaultReps: 10,
      defaultRestSeconds: 105,
      defaultRepsInReserve: 2,
      defaultWeightKg: 18,
      mistakes: [
        ExerciseCueEntry(text: 'Setting the bench too steep'),
        ExerciseCueEntry(text: 'Clashing the dumbbells at the top'),
        ExerciseCueEntry(text: 'Cutting the stretch short'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Bench at 30–45°'),
        ExerciseCueEntry(text: 'Press slightly inward, not straight out'),
        ExerciseCueEntry(text: 'Control the lowering for two seconds'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Dumbbells', text: 'One per hand'),
        ExerciseCueEntry(label: 'Bench', text: 'Adjustable incline bench'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'chest-fly',
      name: 'Cable Chest Fly',
      group: MuscleGroup.chest,
      equipment: Equipment.cable,
      met: 4.5,
      muscleShares: {'Chest': 1, 'Shoulders': 0.3},
      defaultSets: 3,
      defaultReps: 14,
      defaultRestSeconds: 75,
      defaultRepsInReserve: 2,
      defaultWeightKg: 15,
      mistakes: [
        ExerciseCueEntry(text: 'Turning the fly into a press'),
        ExerciseCueEntry(text: 'Locking the elbows straight'),
        ExerciseCueEntry(text: 'Using momentum from the torso'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Soft bend in the elbows throughout'),
        ExerciseCueEntry(text: 'Squeeze the chest at the midline'),
        ExerciseCueEntry(text: 'Open slowly to a full stretch'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Cable', text: 'Dual pulley station'),
        ExerciseCueEntry(label: 'Handles', text: 'One per side'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'push-up',
      name: 'Push Up',
      group: MuscleGroup.chest,
      equipment: Equipment.bodyweight,
      met: 4,
      muscleShares: {'Chest': 1, 'Triceps': 0.55, 'Core': 0.35},
      defaultSets: 3,
      defaultReps: 15,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 3,
      mistakes: [
        ExerciseCueEntry(text: 'Hips sagging toward the floor'),
        ExerciseCueEntry(text: 'Head dropping forward'),
        ExerciseCueEntry(text: 'Half reps'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Body in one straight line'),
        ExerciseCueEntry(text: 'Elbows at roughly 45°'),
        ExerciseCueEntry(text: 'Chest to within a fist of the floor'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Space', text: 'Floor mat')],
    ),
    ExerciseCatalogEntry(
      id: 'pull-up',
      name: 'Pull Up',
      group: MuscleGroup.back,
      equipment: Equipment.bodyweight,
      met: 5,
      muscleShares: {'Back': 1, 'Biceps': 0.6, 'Core': 0.3},
      defaultSets: 4,
      defaultReps: 8,
      defaultRestSeconds: 120,
      defaultRepsInReserve: 2,
      mistakes: [
        ExerciseCueEntry(text: 'Kipping with the legs'),
        ExerciseCueEntry(text: 'Stopping short of the chin'),
        ExerciseCueEntry(text: 'Dropping fast out of the top'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Start from a dead hang'),
        ExerciseCueEntry(text: 'Pull the elbows down to the ribs'),
        ExerciseCueEntry(text: 'Lower over two to three seconds'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Bar', text: 'Pull up bar')],
    ),
    ExerciseCatalogEntry(
      id: 'barbell-row',
      name: 'Barbell Row',
      group: MuscleGroup.back,
      equipment: Equipment.barbell,
      met: 5.5,
      muscleShares: {'Back': 1, 'Biceps': 0.5, 'Hamstrings': 0.25},
      defaultSets: 4,
      defaultReps: 10,
      defaultRestSeconds: 120,
      defaultRepsInReserve: 2,
      defaultWeightKg: 40,
      mistakes: [
        ExerciseCueEntry(text: 'Standing up as the bar rises'),
        ExerciseCueEntry(text: 'Rounding the lower back'),
        ExerciseCueEntry(text: 'Pulling with the arms only'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Hinge to about 45°'),
        ExerciseCueEntry(text: 'Row to the lower ribs'),
        ExerciseCueEntry(text: 'Squeeze the shoulder blades together'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Standard or Olympic bar'),
        ExerciseCueEntry(label: 'Weight plates', text: 'Plus collars/clips'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'lat-pulldown',
      name: 'Lat Pulldown',
      group: MuscleGroup.back,
      equipment: Equipment.cable,
      met: 5,
      muscleShares: {'Back': 1, 'Biceps': 0.5},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 90,
      defaultRepsInReserve: 2,
      defaultWeightKg: 40,
      mistakes: [
        ExerciseCueEntry(text: 'Leaning far back to move the weight'),
        ExerciseCueEntry(text: 'Pulling behind the neck'),
        ExerciseCueEntry(text: 'Letting the shoulders shrug up'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Chest up, slight backward lean'),
        ExerciseCueEntry(text: 'Pull the bar to the collarbone'),
        ExerciseCueEntry(text: 'Control the bar back to full stretch'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Machine', text: 'Lat pulldown station'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'seated-cable-row',
      name: 'Seated Cable Row',
      group: MuscleGroup.back,
      equipment: Equipment.cable,
      met: 5,
      muscleShares: {'Back': 1, 'Biceps': 0.45},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 90,
      defaultRepsInReserve: 2,
      defaultWeightKg: 40,
      mistakes: [
        ExerciseCueEntry(text: 'Rocking the torso back and forth'),
        ExerciseCueEntry(text: 'Rounding the back at the stretch'),
        ExerciseCueEntry(text: 'Short, choppy reps'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Sit tall with a braced core'),
        ExerciseCueEntry(text: 'Draw the handle to the navel'),
        ExerciseCueEntry(text: 'Pause and squeeze at the back'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Machine', text: 'Seated row station'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'face-pull',
      name: 'Face Pull',
      group: MuscleGroup.back,
      equipment: Equipment.cable,
      met: 4,
      muscleShares: {'Shoulders': 1, 'Back': 0.7},
      defaultSets: 3,
      defaultReps: 15,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 3,
      defaultWeightKg: 15,
      mistakes: [
        ExerciseCueEntry(text: 'Going too heavy and using the hips'),
        ExerciseCueEntry(text: 'Pulling below chin height'),
        ExerciseCueEntry(text: 'Shrugging the traps'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Rope set at upper-chest height'),
        ExerciseCueEntry(text: 'Pull toward the forehead, elbows high'),
        ExerciseCueEntry(text: 'Externally rotate at the end range'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Cable', text: 'Rope attachment'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'overhead-press',
      name: 'Overhead Press',
      group: MuscleGroup.shoulders,
      equipment: Equipment.barbell,
      met: 5,
      muscleShares: {'Shoulders': 1, 'Triceps': 0.55, 'Core': 0.3},
      defaultSets: 4,
      defaultReps: 8,
      defaultRestSeconds: 135,
      defaultRepsInReserve: 2,
      defaultWeightKg: 30,
      mistakes: [
        ExerciseCueEntry(text: 'Leaning back excessively'),
        ExerciseCueEntry(text: 'Pressing around the head, not over it'),
        ExerciseCueEntry(text: 'Losing core tension'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Squeeze the glutes and brace hard'),
        ExerciseCueEntry(text: 'Move the head back, then press through'),
        ExerciseCueEntry(text: 'Lock out with the bar over the ears'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Standard or Olympic bar'),
        ExerciseCueEntry(label: 'Rack', text: 'Set at chest height'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'lateral-raise',
      name: 'Lateral Raise',
      group: MuscleGroup.shoulders,
      equipment: Equipment.dumbbell,
      met: 4,
      muscleShares: {'Shoulders': 1},
      defaultSets: 3,
      defaultReps: 15,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 2,
      defaultWeightKg: 8,
      mistakes: [
        ExerciseCueEntry(text: 'Swinging the weights up'),
        ExerciseCueEntry(text: 'Raising above shoulder height'),
        ExerciseCueEntry(text: 'Shrugging the traps'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Slight forward lean, soft elbows'),
        ExerciseCueEntry(text: 'Lead with the elbows, not the hands'),
        ExerciseCueEntry(text: 'Stop level with the shoulders'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Dumbbells', text: 'Light pair'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'barbell-curl',
      name: 'Barbell Curl',
      group: MuscleGroup.arms,
      equipment: Equipment.barbell,
      met: 4,
      muscleShares: {'Biceps': 1},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 75,
      defaultRepsInReserve: 2,
      defaultWeightKg: 20,
      mistakes: [
        ExerciseCueEntry(text: 'Swinging the hips into each rep'),
        ExerciseCueEntry(text: 'Elbows drifting forward'),
        ExerciseCueEntry(text: 'Dropping the bar at the bottom'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Elbows pinned at the ribs'),
        ExerciseCueEntry(text: 'Curl to a full contraction'),
        ExerciseCueEntry(text: 'Lower for three seconds'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Barbell', text: 'Straight or EZ bar'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'triceps-pushdown',
      name: 'Triceps Pushdown',
      group: MuscleGroup.arms,
      equipment: Equipment.cable,
      met: 4,
      muscleShares: {'Triceps': 1},
      defaultSets: 3,
      defaultReps: 14,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 2,
      defaultWeightKg: 25,
      mistakes: [
        ExerciseCueEntry(text: 'Elbows flaring away from the body'),
        ExerciseCueEntry(text: 'Leaning over the bar to press'),
        ExerciseCueEntry(text: 'Cutting the lockout short'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Upper arms locked at the sides'),
        ExerciseCueEntry(text: 'Extend fully and pause'),
        ExerciseCueEntry(text: 'Return under control'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Cable', text: 'Rope or straight bar'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'hammer-curl',
      name: 'Hammer Curl',
      group: MuscleGroup.arms,
      equipment: Equipment.dumbbell,
      met: 4,
      muscleShares: {'Biceps': 1, 'Forearms': 0.6},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 60,
      defaultRepsInReserve: 2,
      defaultWeightKg: 12,
      mistakes: [
        ExerciseCueEntry(text: 'Rotating the wrists mid-rep'),
        ExerciseCueEntry(text: 'Using the shoulders to lift'),
        ExerciseCueEntry(text: 'Rushing the negative'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Neutral grip throughout'),
        ExerciseCueEntry(text: 'Curl one arm at a time if needed'),
        ExerciseCueEntry(text: 'Keep the torso still'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Dumbbells', text: 'One pair')],
    ),
    ExerciseCatalogEntry(
      id: 'plank',
      name: 'Plank',
      group: MuscleGroup.core,
      equipment: Equipment.bodyweight,
      met: 3.5,
      muscleShares: {'Core': 1, 'Shoulders': 0.3},
      defaultSets: 3,
      defaultReps: 45,
      defaultRestSeconds: 45,
      defaultRepsInReserve: 2,
      mistakes: [
        ExerciseCueEntry(text: 'Hips rising too high'),
        ExerciseCueEntry(text: 'Lower back sagging'),
        ExerciseCueEntry(text: 'Holding the breath'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Elbows under the shoulders'),
        ExerciseCueEntry(text: 'Squeeze glutes and brace the abs'),
        ExerciseCueEntry(text: 'Count each second as one rep'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Space', text: 'Floor mat')],
    ),
    ExerciseCatalogEntry(
      id: 'hanging-leg-raise',
      name: 'Hanging Leg Raise',
      group: MuscleGroup.core,
      equipment: Equipment.bodyweight,
      met: 4,
      muscleShares: {'Core': 1, 'Forearms': 0.3},
      defaultSets: 3,
      defaultReps: 12,
      defaultRestSeconds: 75,
      defaultRepsInReserve: 2,
      mistakes: [
        ExerciseCueEntry(text: 'Swinging between reps'),
        ExerciseCueEntry(text: 'Only raising the knees halfway'),
        ExerciseCueEntry(text: 'Dropping the legs quickly'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Start from a controlled dead hang'),
        ExerciseCueEntry(text: 'Curl the pelvis up, not just the legs'),
        ExerciseCueEntry(text: 'Lower slowly to a stop'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Bar', text: 'Pull up bar')],
    ),
    ExerciseCatalogEntry(
      id: 'bodyweight-squat',
      name: 'Bodyweight Squat',
      group: MuscleGroup.legs,
      equipment: Equipment.bodyweight,
      met: 3.5,
      muscleShares: {'Quadriceps': 1, 'Glutes': 0.6},
      defaultSets: 2,
      defaultReps: 15,
      defaultRestSeconds: 45,
      defaultRepsInReserve: 4,
      mistakes: [
        ExerciseCueEntry(text: 'Knees caving inward'),
        ExerciseCueEntry(text: 'Rising onto the toes'),
        ExerciseCueEntry(text: 'Rushing through the reps'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Feet shoulder-width apart'),
        ExerciseCueEntry(text: 'Sit back and down with the chest tall'),
        ExerciseCueEntry(text: 'Use it to warm the hips and knees'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Space', text: 'Floor space')],
    ),
    ExerciseCatalogEntry(
      id: 'hip-flexor-stretch',
      name: 'Hip Flexor Stretch',
      group: MuscleGroup.other,
      equipment: Equipment.bodyweight,
      met: 2.5,
      muscleShares: {'Quadriceps': 0.5, 'Glutes': 0.4},
      defaultSets: 2,
      defaultReps: 30,
      defaultRestSeconds: 30,
      defaultRepsInReserve: 5,
      mistakes: [
        ExerciseCueEntry(text: 'Arching the lower back'),
        ExerciseCueEntry(text: 'Bouncing into the stretch'),
        ExerciseCueEntry(text: 'Holding the breath'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Half-kneeling, tuck the pelvis under'),
        ExerciseCueEntry(text: 'Push the hips gently forward'),
        ExerciseCueEntry(text: 'Hold and breathe, one second per rep'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Space', text: 'Floor mat')],
    ),
    ExerciseCatalogEntry(
      id: 'hamstring-stretch',
      name: 'Hamstring Stretch',
      group: MuscleGroup.other,
      equipment: Equipment.bodyweight,
      met: 2.5,
      muscleShares: {'Hamstrings': 0.6},
      defaultSets: 2,
      defaultReps: 30,
      defaultRestSeconds: 30,
      defaultRepsInReserve: 5,
      mistakes: [
        ExerciseCueEntry(text: 'Rounding the spine to reach further'),
        ExerciseCueEntry(text: 'Locking the knee hard'),
        ExerciseCueEntry(text: 'Pushing into sharp pain'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Hinge from the hips with a flat back'),
        ExerciseCueEntry(text: 'Stop at a mild stretch'),
        ExerciseCueEntry(text: 'Hold and breathe, one second per rep'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Space', text: 'Floor mat')],
    ),
    ExerciseCatalogEntry(
      id: 'foam-roll-quads',
      name: 'Foam Roll Quads',
      group: MuscleGroup.other,
      equipment: Equipment.bodyweight,
      met: 2.5,
      muscleShares: {'Quadriceps': 0.5},
      defaultSets: 2,
      defaultReps: 45,
      defaultRestSeconds: 30,
      defaultRepsInReserve: 5,
      mistakes: [
        ExerciseCueEntry(text: 'Rolling too fast to feel anything'),
        ExerciseCueEntry(text: 'Parking on a joint'),
        ExerciseCueEntry(text: 'Tensing up through the shoulders'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Roll slowly from hip to knee'),
        ExerciseCueEntry(text: 'Pause on tender spots and breathe'),
        ExerciseCueEntry(text: 'Count each second as one rep'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Roller', text: 'Foam roller'),
      ],
    ),
    ExerciseCatalogEntry(
      id: 'rowing-machine',
      name: 'Rowing Machine',
      group: MuscleGroup.cardio,
      equipment: Equipment.machine,
      met: 7,
      muscleShares: {'Back': 0.8, 'Quadriceps': 0.6, 'Core': 0.4},
      defaultSets: 3,
      defaultReps: 120,
      defaultRestSeconds: 90,
      defaultRepsInReserve: 3,
      mistakes: [
        ExerciseCueEntry(text: 'Pulling with the arms first'),
        ExerciseCueEntry(text: 'Rounding the back at the catch'),
        ExerciseCueEntry(text: 'Rushing the recovery'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Drive with the legs, then hinge, then pull'),
        ExerciseCueEntry(text: 'Return in the reverse order'),
        ExerciseCueEntry(text: 'Count each second as one rep'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Machine', text: 'Rower')],
    ),
    ExerciseCatalogEntry(
      id: 'treadmill-intervals',
      name: 'Treadmill Intervals',
      group: MuscleGroup.cardio,
      equipment: Equipment.machine,
      met: 8,
      muscleShares: {'Quadriceps': 0.7, 'Calves': 0.6, 'Hamstrings': 0.4},
      defaultSets: 4,
      defaultReps: 60,
      defaultRestSeconds: 90,
      defaultRepsInReserve: 2,
      mistakes: [
        ExerciseCueEntry(text: 'Holding the handrails while running'),
        ExerciseCueEntry(text: 'Starting the interval too fast'),
        ExerciseCueEntry(text: 'Skipping the walking recovery'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Warm up for three minutes first'),
        ExerciseCueEntry(text: 'Hold a hard but repeatable pace'),
        ExerciseCueEntry(text: 'Count each second as one rep'),
      ],
      equipmentItems: [ExerciseCueEntry(label: 'Machine', text: 'Treadmill')],
    ),
    ExerciseCatalogEntry(
      id: 'kettlebell-swing',
      name: 'Kettlebell Swing',
      group: MuscleGroup.cardio,
      equipment: Equipment.kettlebell,
      met: 6.5,
      muscleShares: {'Glutes': 1, 'Hamstrings': 0.8, 'Core': 0.5},
      defaultSets: 4,
      defaultReps: 15,
      defaultRestSeconds: 75,
      defaultRepsInReserve: 3,
      defaultWeightKg: 16,
      mistakes: [
        ExerciseCueEntry(text: 'Squatting instead of hinging'),
        ExerciseCueEntry(text: 'Lifting the bell with the arms'),
        ExerciseCueEntry(text: 'Leaning back at the top'),
      ],
      guidelines: [
        ExerciseCueEntry(text: 'Hike the bell back between the legs'),
        ExerciseCueEntry(text: 'Snap the hips to float it up'),
        ExerciseCueEntry(text: 'Finish with a hard glute squeeze'),
      ],
      equipmentItems: [
        ExerciseCueEntry(label: 'Kettlebell', text: 'One bell'),
      ],
    ),
  ];

  static const List<WorkoutProgramEntity> programs = [
    WorkoutProgramEntity(
      id: 'strength-builder',
      name: 'Strength Builder',
      description: 'Progressive barbell strength across four sessions a week',
      level: 'Intermediate',
      weeks: 12,
      days: [
        ProgramDayEntry(
          weekday: DateTime.monday,
          name: 'Push Day',
          focus: 'Strength',
          goal: 'Add load to your press.',
          durationMinutes: 50,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'push-up',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-bench-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'overhead-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'incline-db-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'triceps-pushdown',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.tuesday,
          name: 'Pull Day',
          focus: 'Strength',
          goal: 'Own every rep from a dead hang.',
          durationMinutes: 50,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'face-pull',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'pull-up',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-row',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'seated-cable-row',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-curl',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.thursday,
          name: 'Leg Day',
          focus: 'Strength',
          goal: 'Increase squat weight.',
          durationMinutes: 55,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'bodyweight-squat',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hip-flexor-stretch',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-back-squat',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'romanian-deadlift',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'leg-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'walking-lunge',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'leg-extension',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'standing-calf-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.saturday,
          name: 'Upper Accessory',
          focus: 'Hypertrophy',
          goal: 'Chase a clean pump, not a max.',
          durationMinutes: 45,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'push-up',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'lat-pulldown',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'chest-fly',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'lateral-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hammer-curl',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'plank',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
      ],
    ),
    WorkoutProgramEntity(
      id: 'fat-loss-shred',
      name: 'Fat Loss Shred',
      description: 'High-intensity metabolic conditioning',
      level: 'Intermediate',
      weeks: 8,
      days: [
        ProgramDayEntry(
          weekday: DateTime.monday,
          name: 'Full Body Circuit',
          focus: 'Conditioning',
          goal: 'Keep the rest short.',
          durationMinutes: 40,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'bodyweight-squat',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'kettlebell-swing',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'push-up',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'walking-lunge',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'plank',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.tuesday,
          name: 'Intervals',
          focus: 'Cardio',
          goal: 'Hold the pace on every interval.',
          durationMinutes: 35,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'treadmill-intervals',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.wednesday,
          name: 'Upper Circuit',
          focus: 'Conditioning',
          goal: 'Move between sets without stalling.',
          durationMinutes: 40,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'face-pull',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'lat-pulldown',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'incline-db-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'lateral-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'plank',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.friday,
          name: 'Lower Circuit',
          focus: 'Conditioning',
          goal: 'Legs under fatigue, form intact.',
          durationMinutes: 40,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'bodyweight-squat',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'leg-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'walking-lunge',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'standing-calf-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.sunday,
          name: 'Row Conditioning',
          focus: 'Cardio',
          goal: 'Steady, repeatable splits.',
          durationMinutes: 30,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'rowing-machine',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
      ],
    ),
    WorkoutProgramEntity(
      id: 'muscle-hypertrophy',
      name: 'Muscle Hypertrophy',
      description: 'Volume-focused strength and size work',
      level: 'Advanced',
      weeks: 16,
      days: [
        ProgramDayEntry(
          weekday: DateTime.monday,
          name: 'Chest & Triceps',
          focus: 'Hypertrophy',
          goal: 'Add a rep to every top set.',
          durationMinutes: 55,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'push-up',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-bench-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'incline-db-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'chest-fly',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'triceps-pushdown',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.tuesday,
          name: 'Back & Biceps',
          focus: 'Hypertrophy',
          goal: 'Full stretch on every rep.',
          durationMinutes: 55,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'face-pull',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'pull-up',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-row',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'seated-cable-row',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-curl',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hammer-curl',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.thursday,
          name: 'Quad Focus',
          focus: 'Hypertrophy',
          goal: 'Depth before load.',
          durationMinutes: 55,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'bodyweight-squat',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'barbell-back-squat',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'leg-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'leg-extension',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'standing-calf-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.friday,
          name: 'Shoulders & Core',
          focus: 'Hypertrophy',
          goal: 'Strict form on presses.',
          durationMinutes: 45,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'face-pull',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'overhead-press',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'lateral-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hanging-leg-raise',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'plank',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.saturday,
          name: 'Posterior Chain',
          focus: 'Hypertrophy',
          goal: 'Hinge, do not squat.',
          durationMinutes: 50,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'hip-flexor-stretch',
              section: WorkoutSectionKind.warmUp,
            ),
            ProgramExerciseEntry(
              exerciseId: 'romanian-deadlift',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'walking-lunge',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'kettlebell-swing',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
      ],
    ),
    WorkoutProgramEntity(
      id: 'cardio-base',
      name: 'Cardio Base',
      description: 'Low-intensity aerobic base building',
      level: 'All Levels',
      weeks: 6,
      days: [
        ProgramDayEntry(
          weekday: DateTime.tuesday,
          name: 'Easy Row',
          focus: 'Cardio',
          goal: 'Stay conversational.',
          durationMinutes: 30,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'rowing-machine',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.thursday,
          name: 'Tempo Run',
          focus: 'Cardio',
          goal: 'Hold one steady gear.',
          durationMinutes: 35,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'treadmill-intervals',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'foam-roll-quads',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
        ProgramDayEntry(
          weekday: DateTime.sunday,
          name: 'Long Aerobic',
          focus: 'Cardio',
          goal: 'Finish feeling you could go again.',
          durationMinutes: 45,
          exercises: [
            ProgramExerciseEntry(
              exerciseId: 'rowing-machine',
              section: WorkoutSectionKind.main,
            ),
            ProgramExerciseEntry(
              exerciseId: 'plank',
              section: WorkoutSectionKind.coolDown,
            ),
            ProgramExerciseEntry(
              exerciseId: 'hamstring-stretch',
              section: WorkoutSectionKind.coolDown,
            ),
          ],
        ),
      ],
    ),
  ];
}
